profile: ../src/*.c ../src/*.h
	gcc -std=gnu99 -O3 -Wall -pg -DNDEBUG -I../src/ -I../tests/ ../src/*.c test.c -o profile

time: ../src/*.c ../src/*.h
	gcc -std=gnu99 -O3 -Wall -DNDEBUG -I../src/ -I../tests/ ../src/*.c test.c -o time

