// ****************************************************************************
// A small C program to create DIMACS CNF files that encode the pigeonhole
// problem (i.e. placing n+1 pigeons into n holes).
//
// The SAT encoding of this problem is very straightforward.  For each pigeon i
// and each hole j we have a variable x_{n*(i-1)+j} which means that pigeon i
// is placed in hole j.  Then we have n+1 clauses which say that a pigeon has
// to be placed in some hole.  Then for each hole we have a set of clauses
// ensuring that only one single pigeon is placed into that hole.
//
// This encoding leads to a total of (n+1) * n propositional variables and
// (n+1) + n * (n * (n+1) / 2) clauses.
//
// The resulting SAT problem is unsatisfiable.
//
// Version 1.0, 2007-03-15
// (c) 2007 Tjark Weber
//
// I've added output for functional SAT. -- Christoph Schwering
// ****************************************************************************

#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void usage() {
  printf("Usage:\n");
  printf("\n");
  printf("  pigeonhole n\n");
  printf("\n");
  printf("where n>0 is the number of holes (the number of pigeons is n+1).\n");
  exit(1);
}

int main(int argc, char** argv) {

  int n;  // n+1 pigeons in n holes

  int i, k;  // pigeons i, k
  int j;     // hole j

  bool prop = true;

  if (argc <= 1)
    usage();

  for (i = 0; i < argc; ++i) {
    if (sscanf(argv[i], "%d", &n) == 1) {
    } else if (!strcmp(argv[i], "cnf")) {
      prop = true;
    } else if (!strcmp(argv[i], "fcnf")) {
      prop = false;
    }
  }

  if (n < 1)
    usage();

  // DIMACS header
  printf("c pigeon-%d: placing %d pigeons into %d holes\n", n, n+1, n);
  printf("c %s version\n", prop ? "propositional" : "functional");
  printf("c \n");
  printf("c File generated by 'pigeonhole', (c) Tjark Weber\n");
  printf("c \n");
  if (prop) {
    printf("c The propositional SAT encoding of this problem is very straightforward.\n");
    printf("c For each pigeon i and each hole j we have a variable x_{n*(i-1)+j} which\n");
    printf("c means that pigeon ic is placed in hole j. Then we have n+1 clauses which\n");
    printf("c say that a pigeon has to be placed in one of the n holes. Then for each\n");
    printf("c hole we have a set of clauses ensuring that only one single pigeon is\n");
    printf("c placed into that hole.\n");
  } else {
    printf("c The functional SAT encoding of this problem is very straightforward.\n");
    printf("c For each pigeon i we use a function that maps to a hole the pigeon is in.\n");
    printf("c Then we have n+1 clauses which say that a pigeon has to be placed in one\n");
    printf("c of the n holes. Then for pair of pigeons we have n clauses saying that the\n");
    printf("c two pigeons cannot be in the same hole.\n");
  }
  printf("c \n");
  printf("c This encoding leads to a total of (n+1) * n propositional variables and\n");
  printf("c (n+1) + n * (n * (n+1) / 2) clauses.\n");
  printf("c \n");
  printf("c The resulting SAT problem is unsatisfiable.\n");
  printf("c \n");
  if (prop) {
    printf("p cnf %d %d\n", (n+1) * n, (n+1) + n * (n * (n+1) / 2));

    // n+1 clauses which say that a pigeon has to be placed in some hole
    for (i=1; i <= n+1; i++) {
      for (j=1; j <= n; j++)
        printf("%d ", n*(i-1)+j);
      printf("0\n");
    }

    // for each hole we have a set of clauses ensuring that only one single
    // pigeon is placed into that hole
    for (j=1; j <= n; j++)
      for (i=1; i <= n; i++)
        for (k=i+1; k <= n+1; k++)
          printf("-%d -%d 0\n", n*(i-1)+j, n*(k-1)+j);
  } else {
    printf("p fcnf %d %d %d\n", (n+1), n, (n+1) + n * (n * (n+1) / 2));


    // n+1 clauses, each of which says that one specific pigeon must be in
    // one of the holes
    for (i=1; i <= n+1; i++) {
      for (j=1; j <= n; j++)
        printf("%3d = %2d   ", i, j);
      printf("0\n");
    }

    // no two pigeons must go into the same hole
    for (j=1; j <= n; j++)
      for (i=1; i <= n+1; i++)
        for (k=i+1; k <= n+1; k++)
          printf("%3d = %2d   %3d = %2d   0\n", -i, j, -k, j);
  }

  return 0;
}
